src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Serializer\Normalizer\NormalizableInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket implements NormalizableInterface
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'is_done')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column]
    private ?bool $is_done = false;

    #[ORM\OneToMany(mappedBy: 'ticket', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'tickets')]
    #[Assert\NotBlank]
    private Collection $tags;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function isIsDone(): ?bool
    {
        return $this->is_done;
    }

    public function setIsDone(bool $is_done): static
    {
        $this->is_done = $is_done;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTicket($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTicket() === $this) {
                $comment->setTicket(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }


    public function normalize(NormalizerInterface $normalizer, string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        return [
            'title' => $this->getTitle(),
            'content' => $this->getTitle(),
            'created_at' => $this->getCreatedAt(),
            'updated_at' => $this->getUpdatedAt()
        ];
    }
}

templates/components/Alert.html.twig
{% for type, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert alert-{{ type }} mb-5">
            {% if type == 'info' %}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>

            {% elseif type == 'success' %}
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>

            {% elseif type == 'warning' %}
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>

            {% elseif type == 'error' %}
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>

            {% endif %}
            <span>{{ message }}</span>
        </div>
    {% endfor %}
{% endfor %}

templates/components/Comment.html.twig
<div {{ attributes }}>
    <h3>{{ comment.author.email }}</h3>
    <p>{{ comment.content }}</p>
    {% if app.user == comment.author %}
        <div class="inline-flex gap-5">
            <small class="">
                <a href="{{ path('app_comment_delete', {'id': comment.id}) }}" class="inline-flex gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                    <span>Delete my comment</span>
                </a>
            </small>
            <small class="">
                <a href="{{ path('app_comment_delete', {'id': comment.id}) }}" class="inline-flex gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                    </svg>

                    <span>Update my comment</span>
                </a>
            </small>
        </div>
    {% endif %}
</div>
<div class="divider"></div>

templates/components/RegistrationForm.html.twig
<div class="prose mx-auto" {{ attributes }}>
    <h1 class="text-center">Register</h1>

    {{ form_start(form, {
        attr: {
            class: 'gap-5 form-control',
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|register',
        }
    }) }}

        <div class="form-control">
            <label class="label">
                <span class="label-text">{{ form_label(form.email) }}</span>
            </label>
            {{ form_widget(form.email, {
                attr: {
                    class: 'input input-bordered w-full'
                }
            }) }}
            <small class="text-error font-bold">{{ form_errors(form.email) }}</small>
        </div>

        <div class="form-control gap-5">
            {% for passwordField in form.password %}
                <div class="form-control">
                    <label class="label">
                        <span class="label-text">{{ form_label(passwordField) }}</span>
                    </label>
                    {{ form_widget(passwordField, {
                        attr: {
                            class: 'input input-bordered w-full'
                        }
                    }) }}
                    <small class="text-error">{{ form_errors(passwordField) }}</small>
                </div>
            {% endfor %}
        </div>

        <div class="form-control">
            <label class="cursor-pointer label">
                <span class="label-text">{{ form_label(form.agreeTerms) }}</span>
                {{ form_widget(form.agreeTerms, {
                    attr: {class: 'checkbox'}
                }) }}
            </label>
            <small class="text-error">{{ form_errors(form.agreeTerms) }}</small>
        </div>

        {{ form_rest(form) }}

        <button type="submit" class="btn btn-primary w-full" {{ this.hasValidationErrors ? 'disabled' : '' }}>Register</button>
    {{ form_end(form) }}
</div>

templates/components/TicketDetails.html.twig
<div class="prose-sm" {{ attributes }}>
    <div class="flex justify-between w-full">
        <h1>{{ ticket.title }}</h1>
        {% if ticket.author == app.user %}
            <button class="btn" onclick="postOptions.showModal()">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 1 1-3 0m3 0a1.5 1.5 0 1 0-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-9.75 0h9.75" />
                </svg>
            </button>
        {% endif %}
    </div>

    <p>{{ ticket.content }}</p>
    <small>{{ ticket.author.email }}</small>
</div>

<dialog id="postOptions" class="modal modal-bottom sm:modal-middle">
    <div class="modal-box">
        <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
        </form>
        <h3 class="font-bold text-lg">Post settings</h3>
        <p class="py-4">From here, you can either update, delete or mark your ticket as resolved</p>
        <div class="modal-action">
            {% if not ticket.isDone %}
                <a href="{{ path('ticket_update', {id: ticket.id}) }}" class="btn btn-warning">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                    </svg>

                    Update
                </a>
            {% endif %}
            <a href="{{ path('app_ticket_delete', {id: ticket.id}) }}" class="btn btn-error">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>

                Delete
            </a>
            {% if not ticket.isDone %}
                <a href="{{ path('ticket_resolve', {id: ticket.id}) }}" class="btn btn-success">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                    </svg>

                    Mark as resolved
                </a>
            {% endif %}
        </div>
    </div>
</dialog>

templates/components/TicketForm.html.twig
<div class="prose mx-auto" {{ attributes }}>
    <h1 class="text-center">Register</h1>

    {{ form_start(form, {
        attr: {
            class: 'gap-5 form-control',
            'novalidate': true,
            'data-action': 'live#action',
            'data-action-name': 'prevent|create',
        }
    }) }}

        <div class="form-control">
            <label class="label">
                <span class="label-text">{{ form_label(form.title) }}</span>
            </label>
            {{ form_widget(form.title, {
                attr: {
                    class: 'input input-bordered w-full'
                }
            }) }}
            <small class="text-error font-bold">{{ form_errors(form.title) }}</small>
        </div>

        <div class="form-control">
            <label class="label">
                <span class="label-text">{{ form_label(form.content) }}</span>
            </label>
            {{ form_widget(form.content, {
                attr: {
                    class: 'textarea textarea-bordered w-full'
                }
            }) }}
            <small class="text-error font-bold">{{ form_errors(form.content) }}</small>
        </div>

        <div class="form-control">
            <label class="label">
                <span class="label-text">{{ form_label(form.tags) }}</span>
            </label>
            {{ form_widget(form.tags, {
                attr: {
                    class: ''
                }
            }) }}
            <small class="text-error font-bold">{{ form_errors(form.tags) }}</small>
        </div>

        {{ form_rest(form) }}

        <button type="submit" class="btn btn-primary w-full" {{ this.hasValidationErrors ? 'disabled' : '' }}>Register</button>

    {{ form_end(form) }}
</div>

templates/components/TicketItem.html.twig
<a href="{{ path('ticket_read', {id: ticket.id}) }}" class="card w-full bg-base-100 hover:shadow transition-all duration-500 hover:border-primary border">
    <div class="card-body">
        <h2 class="card-title">{{ ticket.title }}</h2>
        <p>{{ticket.content|u.truncate(120, '...')}}</p>
        <div class="card-actions justify-start gap-5">
            <small class="inline-flex gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 0 1-.825-.242m9.345-8.334a2.126 2.126 0 0 0-.476-.095 48.64 48.64 0 0 0-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0 0 11.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
                </svg>

                {{ ticket.getComments|length }} Comments
            </small>

            <small class="inline-flex gap-2">
                Posted by {{ ticket.author.email }}
            </small>
        </div>
    </div>
</a>